### ISSUE TITLE
getting messages for anyone elses kills

### ISSUE THREAD

**Issue by ghost** [GaryTheNoTrashCougar/Arma3-KillNotificationHUD#1]
whenever anyone gets a kill it comes up with enemy killed on my screen like i have killed them

**Comment by GaryTheNoTrashCougar** [comment]
I have updated & hopefully fixed this. Let me know if it works. Not 100% sure what I'm doing tbh lol.

**Comment by ghost** [comment]
all good im the same. if you need any help i can do some of the basic stuff with some guidance

**Comment by GaryTheNoTrashCougar** [comment]
At some point I will try to make the points stack for a moment after each kill.  My first attempts at doing this have somewhat worked.  I can suspend the script that resets the points after the first kill, but trying to get the time delay to stack after every kill is proving difficult.  Maybe a limitation & might not be possible or I simply cannot do the maths lol.

**Comment by GaryTheNoTrashCougar** [comment]
I take it as you said 'all good' the issue has been fixed, so I will close this.  If there are any other problems do let me know.  Haven't got round to fully testing this, only solo.  Thanks

**Comment by ghost** [comment]
hey only just got around to testing it with other players but i still get notifications for their kills

**Comment by ghost** [comment]
and you lost me at point stack so i think this script is going to be a bit out of my scripting knowledge

**Comment by GaryTheNoTrashCougar** [comment]
Let's try running the script at mission start.  I've replaced initPlayerLocal.sqf with init.sqf, see if that works.

**Comment by ghost** [comment]
i called it from the init.sqf and still showing me other peoples kills. amazing script by the way! looks so good

**Comment by ghost** [comment]
would initclient.sqf or init_client.sqf work?

**Comment by GaryTheNoTrashCougar** [comment]
Not sure if those are event scripts.  I don't think it's anything to do with how the script is fired, initPlayerLocal, what I originally used is local (on client's machine). Possibly my arguments are incorrect.  I will try BI forums see if anyone can point out my mistake.  It could be because I haven't specifically called the kill message to show on the killer's screen only.

**Comment by GaryTheNoTrashCougar** [comment]
Does it show all the different messages or just enemy killed?

**Comment by ghost** [comment]
Yeah its probably the not called to player screen only. And all messages, longshot, headshot etc

**Comment by GaryTheNoTrashCougar** [comment]
Hopefully this should work now.  I don't have a server set up to test with other players so if you wouldn't mind testing again when you get chance & let me know if it's working.  Thanks

**Comment by ghost** [comment]
Just tested now and the messages are still global

**Comment by GaryTheNoTrashCougar** [comment]
I have updated again.  If this doesn't work I may have to wait until someone gets back to me on BI forums.  I'm not so good at multiplayer scripting.  It's a nightmare.

**Comment by GaryTheNoTrashCougar** [comment]
Maybe now it will work.  I've resorted to a check to see if the killer is local as a work around, as it turns out the event handler is firing on every machine.  I've also changed a few arguments & added a road kill message, seems to work in a multiplayer environment but not tested on dedicated server with other players yet.  That will be down to you lol.  Thanks

**Comment by ghost** [comment]
fixed!!! works perfect, thank you very much

**Comment by GaryTheNoTrashCougar** [comment]
Got there in the end lol.  Thanks for testing it.  I've updated it again. Cleaned it up a bit + I was getting headshot notifications at the wrong time so I've narrowed down the conditions.  Have fun & thank you.
